name: Build and Deploy Docs

on:
  workflow_dispatch:

jobs:
  release-docs:
    uses: scikit-package/release-scripts/.github/workflows/_release-docs.yml@v0
    with:
      project: diffpy.apps
      python_version: 3.13
